services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["npm", "run", "dev"]
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      WB_TARIFFS_BOX_URL: ${WB_TARIFFS_BOX_URL}
      WB_TARIFFS_AUTH_TOKEN: ${WB_TARIFFS_AUTH_TOKEN}
      WB_TARIFFS_QUEUE_NAME: ${WB_TARIFFS_QUEUE_NAME}
      WB_TARIFFS_JOB_ATTEMPTS: ${WB_TARIFFS_JOB_ATTEMPTS}
      WB_TARIFFS_BACKOFF_DELAY_MS: ${WB_TARIFFS_BACKOFF_DELAY_MS}
      WB_TARIFFS_WORKER_CONCURRENCY: ${WB_TARIFFS_WORKER_CONCURRENCY}
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - postgres-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["npm", "run", "dev:worker"]
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      WB_TARIFFS_BOX_URL: ${WB_TARIFFS_BOX_URL}
      WB_TARIFFS_AUTH_TOKEN: ${WB_TARIFFS_AUTH_TOKEN}
      WB_TARIFFS_QUEUE_NAME: ${WB_TARIFFS_QUEUE_NAME}
      WB_TARIFFS_JOB_ATTEMPTS: ${WB_TARIFFS_JOB_ATTEMPTS}
      WB_TARIFFS_BACKOFF_DELAY_MS: ${WB_TARIFFS_BACKOFF_DELAY_MS}
      WB_TARIFFS_WORKER_CONCURRENCY: ${WB_TARIFFS_WORKER_CONCURRENCY}
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    networks:
      - postgres-net

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["npx", "tsx", "src/scheduler-init.ts"]
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      WB_TARIFFS_BOX_URL: ${WB_TARIFFS_BOX_URL}
      WB_TARIFFS_AUTH_TOKEN: ${WB_TARIFFS_AUTH_TOKEN}
      WB_TARIFFS_QUEUE_NAME: ${WB_TARIFFS_QUEUE_NAME}
      WB_TARIFFS_JOB_ATTEMPTS: ${WB_TARIFFS_JOB_ATTEMPTS}
      WB_TARIFFS_BACKOFF_DELAY_MS: ${WB_TARIFFS_BACKOFF_DELAY_MS}
      WB_TARIFFS_WORKER_CONCURRENCY: ${WB_TARIFFS_WORKER_CONCURRENCY}
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    networks:
      - postgres-net

  sheets-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["npx", "tsx", "src/sheets.worker.ts"]
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      SHEETS_TARIFFS_SHEET_NAME: ${SHEETS_TARIFFS_SHEET_NAME}
      GOOGLE_CREDENTIALS_PATH: ${GOOGLE_CREDENTIALS_PATH}
      EXPORT_TIMEZONE: ${EXPORT_TIMEZONE}
      SHEETS_EXPORT_CRON: ${SHEETS_EXPORT_CRON}
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - postgres-net

  sheets-scheduler-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["npx", "tsx", "src/sheets.scheduler-init.ts"]
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      SHEETS_TARIFFS_SHEET_NAME: ${SHEETS_TARIFFS_SHEET_NAME}
      GOOGLE_CREDENTIALS_PATH: ${GOOGLE_CREDENTIALS_PATH}
      EXPORT_TIMEZONE: ${EXPORT_TIMEZONE}
      SHEETS_EXPORT_CRON: ${SHEETS_EXPORT_CRON}
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - postgres-net
